### PR TITLE
fix: Move /api/client/register to a post request.

### LINKED ISSUE #80: Edge doesn't accept metrics from SDK clients
### Describe the bug

When running Edge in edge mode, no metrics are posted upstream.

### Steps to reproduce the bug

1. Start edge
2. Connect SDK
3. See no metrics being posted upstream

### Expected behavior

Metrics to be posted upstream

### Logs, error output, etc.

_No response_

### Screenshots

_No response_

### Additional context

This is due to a mistake in HTTP method mapping for /api/client/metrics. It has been set to GET instead of POST.

### Unleash version

_No response_

### Subscription type

None

### Hosting type

None

### SDK information (language and version)

_No response_

### PR DESCRIPTION
**Pull request by chriswk**
Earlier we didn't accept metrics from downstream clients because we made a wrong assumption about Request Method type. This PR fixes this and starts accepting client metrics and posting them upstream.

There's a PR open on Unleash to make sure ConnectVia on unleash side is also expecting the { appName, instanceId } struct - https://github.com/Unleash/unleash/pull/3213

Closes #80

### CODE REVIEW

**Review by sighphyre — APPROVED** [review]
G

File: server/src/cli.rs [hunk 1]
```diff
@@ -64,6 +64,14 @@ pub struct CliArgs {
 
     #[command(subcommand)]
     pub mode: EdgeMode,
+
+    /// Instance id. Used for metrics reporting
```
Comment (nunogois) [inline server/src/cli.rs:68]:
```suggestion
    /// Instance id. Used for metrics reporting.
```

**Review by nunogois — APPROVED** [review]
LGTM
