### PR TITLE
fix: frontend all endpoints now accept context correctly

### LINKED ISSUE #555: Context properties are not evaluated when using /api/proxy/all
### Describe the bug

Contextual properties should be evaluated in the same way regardless of the routing /api/proxy/all, /api/proxy or /api/frontend

### Steps to reproduce the bug

1. Create a strategy that uses context properties such as the ones defined in the test file `with_custom_constraint.json`

2. Call the API using `/api/proxy/all?properties[companyId]=bricks`

3. The strategy will not match the output of `/api/frontend?properties[companyId]=bricks` or `/api/proxy?properties[companyId]=bricks`

### Expected behavior

Contextual properties from /api/proxy/all should be evaluated in the same way than /api/frontend and /api/proxy.
In that case the flag should be `enabled` when `companyId=bricks`

### Logs, error output, etc.

_No response_

### Screenshots

_No response_

### Additional context

# Client impact
/api/proxy/all is mandatory for Dart SDK users to be able to rely on edge to fetch unleash flags and ensure metrics propagation 

# How to reproduce the issue usings tests
The test `can_handle_custom_context_fields` in `frontend_api.rs` does not check the flag `enabled` property.
This code allows to see the difference between the different endpoints.

```
        let req = test::TestRequest::get()
            .uri("/api/frontend?properties[companyId]=bricks")
            .insert_header(ContentType::json())
            .insert_header(("Authorization", auth_key.clone()))
            .to_request();
        let no_escape: FrontendResult = test::call_and_read_body_json(&app, req).await;
        assert!(no_escape.toggles.iter().all(|toggle| toggle.enabled));

        let req = test::TestRequest::get()
            .uri("/api/proxy?properties[companyId]=bricks")
            .insert_header(ContentType::json())
            .insert_header(("Authorization", auth_key.clone()))
            .to_request();
        let no_escape: FrontendResult = test::call_and_read_body_json(&app, req).await;
        assert!(no_escape.toggles.iter().all(|toggle| toggle.enabled));

        let req = test::TestRequest::get()
        .uri("/api/proxy/all?properties[companyId]=bricks")
        .insert_header(ContentType::json())
        .insert_header(("Authorization", auth_key.clone()))
        .to_request();
        let no_escape: FrontendResult = test::call_and_read_body_json(&app, req).await;
        assert!(no_escape.toggles.iter().all(|toggle| toggle.enabled));
```
Note: The flags are evaluated correctly with the custom properties using POST calls but not on the ones that rely on GET such as the ones from the Flutter / Dart SDK.

### Unleash version

v19.5.0

### Subscription type

Enterprise

### Hosting type

Self-hosted

### SDK information (language and version)

curl and Dart SDK

### PR DESCRIPTION
**Pull request by sighphyre**
Moves the all endpoints for the frontend API to use the same context parsing path as the non all endpoints. Fixes an issue where context properties would not be correctly considered in the feature evaluation

Closes #555

### CODE REVIEW

File: server/src/frontend_api.rs [hunk 1]
```diff
@@ -746,20 +747,16 @@ pub fn get_all_features(
...
-    let context: Context = raw_context.into();
     let context_with_ip = if context.remote_address.is_none() {
         Context {
             remote_address: client_ip.map(|ip| ip.to_string()),
-            ..context
+            ..context.clone()
         }
     } else {
-        context
+        context.clone()
```
Comment (gastonfournier) [inline server/src/frontend_api.rs:759]: I wonder if we do have to clone here, there's no risk other than a bit more of memory allocation

**Review by gastonfournier — APPROVED** [review]
LG!

File: server/src/frontend_api.rs (hunk 1 above)
Comment (sighphyre) [reply server/src/frontend_api.rs]: The clone here is pretty light, in this context it's probably over optimizing to fix given the amount of memory that's consumed in processing an HTTP request

...but it looks dumb and it's easy to fix so yeah, I took it out! Good eyes!
